"""empty message

Revision ID: 6124f8c938c2
Revises: 071d6c632cf5
Create Date: 2024-06-08 22:19:22.903477

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6124f8c938c2'
down_revision = '071d6c632cf5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint('user_last_name_key', type_='unique')
        batch_op.drop_constraint('user_name_key', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_unique_constraint('user_name_key', ['name'])
        batch_op.create_unique_constraint('user_last_name_key', ['last_name'])

    # ### end Alembic commands ###
